### ISSUE TITLE
Fix missing translation

### ISSUE THREAD

**Issue by davidromani** [AgustiCalafellSegura/untitled#1]
Translate to english line 5 in README.md file

**Comment by davidromani** [comment]
@AgustiCalafellSegura well done, I saw that you finished this issue in [this](https://github.com/AgustiCalafellSegura/untitled/commit/2b719d3f16c2cb1e71f08db2e71ed35dc4fc4bc7) commit. Now, you can close the issue, ok?

**Comment by AgustiCalafellSegura** [comment]
How I can close the issue?

2017-09-17 20:29 GMT+02:00 David Romaní <notifications@github.com>:

**Comment by davidromani** [comment]
@AgustiCalafellSegura open this URL https://github.com/AgustiCalafellSegura/untitled/issues/1 and click on "Close" button... easy ;-)

**Comment by AgustiCalafellSegura** [comment]
Okey. It's done.

2017-09-17 20:36 GMT+02:00 David Romaní <notifications@github.com>:
