### ISSUE TITLE
Create a devel branch

### ISSUE THREAD

**Issue by davidromani** [AgustiCalafellSegura/untitled#2]
One of the most interesting features in Git are branches. A branch is like a parallel timeline where you can put more commits. 

It's very common to have a "master" branch and a "devel" branch. When you start to develop new source code, you must do it in a devel branch. Of course, all the new required code needs more commits. 

When you think that the new code is finished, for example, when a new feature of the app is done, then we will merge all commits of devel branch into master branch.

So for now, follow this instructions:

1. create a new Git branch called "devel" in your local repository
2. add a new "index.html" file
3. write some code inside
4. create a new commit
5. and push this commit to Github (your remote repository)

**Comment by davidromani** [comment]
@AgustiCalafellSegura how is this issue going? any problem?

**Comment by AgustiCalafellSegura** [comment]
I was with my family in Ibiza, so i couldn't do anything. Sorry.

**Comment by AgustiCalafellSegura** [comment]
I create the branch devel, the file with some text inside, the new commit and the push. But i don't see something new in github. What I did wrong?

**Comment by davidromani** [comment]
@AgustiCalafellSegura you must push to Github with this command `git push origin devel` and remember to create a new commit before pushing.

**Comment by AgustiCalafellSegura** [comment]
I did but only push the branch but not the index.html and the commit :-(

**Comment by davidromani** [comment]
@AgustiCalafellSegura sure? I can see index.html inside devel branch here... https://github.com/AgustiCalafellSegura/untitled/commits/devel

**Comment by davidromani** [comment]
@AgustiCalafellSegura well done, shortly I will create a new issue with another challenge. Meanwhile check this graph https://github.com/AgustiCalafellSegura/untitled/network and try to understand it.
