### ISSUE TITLE
Use Composer as a PHP package manager

### ISSUE THREAD

**Issue by davidromani** [AgustiCalafellSegura/untitled#3]
Here we go! Next challenge it's a little bit harder...

1. install composer into your project root folder following [this](https://getcomposer.org/download/) instructions
2. pull remote changes (my latest Github commits) into your local devel banch
3. execute `composer.phar install` command from your project root folder
4. check that a new directory called "vendor" have been created inside your project root folder 

Tell me something when you have finished it.

**Comment by AgustiCalafellSegura** [comment]
I do it 1 without problems but the 2, 3 and 4 I had problems. I don't know how do it.

**Comment by davidromani** [comment]
@AgustiCalafellSegura to solve step 2, read [this](https://es.atlassian.com/git/tutorials/atlassian-git-cheatsheet) cheat sheet and try to find the solution inside "remote repositories" section. Good luck!

**Comment by AgustiCalafellSegura** [comment]
That will help me, thanks!

**Comment by AgustiCalafellSegura** [comment]
![seleccion_001](https://user-images.githubusercontent.com/31628026/31083068-eabfc42e-a790-11e7-8215-da029adf71f0.png)

**Comment by AgustiCalafellSegura** [comment]
I can't do the third one

**Comment by davidromani** [comment]
done
