### ISSUE TITLE
Merging branches

### ISSUE THREAD

**Issue by davidromani** [AgustiCalafellSegura/untitled#4]
Now it's time to know how to merge devel commits into master branch. So follow these steps:

1. `git checkout master`
2. `git merge --no-ff master`
3. `git push origin master`
4. `git checkout devel`

Tip: have a look [here](https://www.atlassian.com/git/tutorials/atlassian-git-cheatsheet) and try to understand better these commands

**Comment by AgustiCalafellSegura** [comment]
I did it but i didn't see the changes un smartgit

**Comment by davidromani** [comment]
Because you didn't done well. Try to copy the commands output (results) here.

**Comment by AgustiCalafellSegura** [comment]
![seleccion_004](https://user-images.githubusercontent.com/31628026/31483378-687f1e44-af2c-11e7-9745-f5fdc0f3056b.png)

**Comment by davidromani** [comment]
@AgustiCalafellSegura sorry, I did a mistake, repeat all the steps again but replace step 2 by this command:

```
2. git merge --no-ff devel
```

**Comment by AgustiCalafellSegura** [comment]
![seleccion_005](https://user-images.githubusercontent.com/31628026/31501553-d7a9a47c-af6a-11e7-8b6b-11025b09f29c.png)
![seleccion_005](https://user-images.githubusercontent.com/31628026/31501560-dc5b5f60-af6a-11e7-9ce7-9ee58cfaad5c.png)
![seleccion_006](https://user-images.githubusercontent.com/31628026/31501562-dca79e34-a

**Comment by AgustiCalafellSegura** [comment]
![seleccion_005](https://user-images.githubusercontent.com/31628026/31501576-eee237da-af6a-11e7-8535-f66da5f7e397.png)
![Uploading Selección_006.png…]()

**Comment by AgustiCalafellSegura** [comment]
![seleccion_006](https://user-images.githubusercontent.com/31628026/31501612-02b06a84-af6b-11e7-8db9-02c918a3d8e1.png)

**Comment by davidromani** [comment]
Ok, it's done. 

See [this](https://github.com/AgustiCalafellSegura/untitled/network) graph to see what happened. Tell me something if you don't understand what happened, ok?
