### ISSUE TITLE
Test Command

### ISSUE THREAD

**Issue by davidromani** [AgustiCalafellSegura/untitled#5]
Hi.

I've pushed some new commits into devel branch. Pull it into your local repository and then try to execute this command:

```bash
$ ./console.php app:test
```

Check that you can see a "Hello World" message in your output terminal. So, now it's time to start some plain PHP coding...

Try to improve the `execute` method in TestCommand class to show 10 "Hello World" messages instead of only 1.

**Comment by AgustiCalafellSegura** [comment]
![seleccion_007](https://user-images.githubusercontent.com/31628026/31558429-13b0c030-b04d-11e7-81d3-d995ec37333b.png)

**Comment by davidromani** [comment]
@AgustiCalafellSegura ok, but you still needing to change some code in src/TestCommand.php file to print 10 "Hello World" messages...

**Comment by AgustiCalafellSegura** [comment]
I try but i can't do anything with execute method. It will be like execute 10 hello.php, but I can't do.

**Comment by davidromani** [comment]
@AgustiCalafellSegura why not? Read [this](https://github.com/AgustiCalafellSegura/untitled/blob/devel/src/TestCommand.php) class an tell me in which line a "Hello world" message is printed. Then you only need to write some new code there...

**Comment by AgustiCalafellSegura** [comment]
36     $output->writeln('Hello World!');

I just have to do for example a for to print that message 10 times?

**Comment by davidromani** [comment]
@AgustiCalafellSegura think a little bit about it... you have an example to print 1 message, so try to write 10 messages

**Comment by AgustiCalafellSegura** [comment]
![seleccion_008](https://user-images.githubusercontent.com/31628026/31636999-0e7b068e-b2cd-11e7-9a0f-87a4d0982063.png)

**Comment by AgustiCalafellSegura** [comment]
Done! :-)
