### ISSUE TITLE
Command input arguments

### ISSUE THREAD

**Issue by davidromani** [AgustiCalafellSegura/untitled#6]
Now it's time to make same command a little bit more dynamic. You've to read an input argument to define how many times "Hello World" message has to be printed.

Read the "Console input" section [here](https://symfony.com/doc/2.8/console.html#console-input) and add an argument called "times" to achieve this behaviour:

```bash
$ ./console.php app:test 100

Hello World 2!
Hello World 4!
Hello World 6!
Hello World 8!
(...)
Hello World 98!
Hello World 100!
```

**Comment by AgustiCalafellSegura** [comment]
![captura 3445](https://user-images.githubusercontent.com/31628026/31991529-47d725f0-b978-11e7-8f66-c7c489673c16.PNG)

**Comment by AgustiCalafellSegura** [comment]
Should I create an argument that execute that 100 times?

**Comment by davidromani** [comment]
@AgustiCalafellSegura yes, you must create a required argument that can be dynamic. For exemple, same command can print 100 messages or 50 messages...

**Comment by AgustiCalafellSegura** [comment]
What name i should write for a file? I made a sentence that read how many times you want to execute but i don't know where to create a new file and which name that will have.

**Comment by davidromani** [comment]
@AgustiCalafellSegura no new file needed, you only need to declare (add) an argument inside `configure` function (method) and then use it in `execute` function

**Comment by AgustiCalafellSegura** [comment]
I don't know how to do it with arguments. With one function i can do it but i don't know how to do it right now.
