### ISSUE TITLE
Create a calculator command

### ISSUE THREAD

**Issue by davidromani** [AgustiCalafellSegura/untitled#7]
Create a new command with **two** input arguments that prints this results. Rember that values 3 and 7 are only an example. Your command must operate with **any** input values.

```bash
$ ./console.php app:calculator 3 7

The greather number is: 7
3 + 7 = 10
3 - 7 = -4
3 * 7 = 21
3 ÷ 7 = 0.43
3 ^ 7 = 2187
```

**Comment by davidromani** [comment]
@AgustiCalafellSegura any question about this issue?

Remember that I need **another** command, so keep intact the first command (TestCommand class) and create another command class...

**Comment by AgustiCalafellSegura** [comment]
I don't understand. Should I comment the last exercise?

**Comment by davidromani** [comment]
Keep the file src/TestCommand.php as a command to print "Hello World" messages and create another file src/CalculatorCommand.php file with the new behaviour.

Have you ever worked with Object Oriented Programming (OOP)? Do you know what is a class and an object?

Feel free to say no, it doesn't matter because I only need to discover your real programming level to manage the difficult of the exercises (issues).

**Comment by AgustiCalafellSegura** [comment]
Okey. I will do. I just didn't understand. I worked a little bit with Object Oriented Programming, but i will give the best.

**Comment by AgustiCalafellSegura** [comment]
I create the CalculatorCommand.php but i can not execute correctly. I don't know what is wrong.

**Comment by davidromani** [comment]
Please, push all of your changes. I can't help you if you don't push the CalculatorCommand class.

**Comment by davidromani** [comment]
Ok, now let's to fix some problems...

* Problem 1: two numbers can be equals, then you must improve to output message to say it
```bash
$ ./console.php app:calculator 14 14

Both numbers are equals.
14 + 14 = 28
14 - 14 = 0
14 * 14 = 196
14 / 14 = 1
14 ^ 14 = 11112006825558016
```

* Problem 2: handle division by zero exception, you must check if number2=0 and say this message
```bash
$ ./console.php app:calculator 11 0

The greather number is: 11
11 + 0 = 11
11 - 0 = 11
11 * 0 = 0
11 / 0 = impossible to divide
11 ^ 0 = 1
```
