### ISSUE TITLE
Symfony Validator Component

### ISSUE THREAD

**Issue by davidromani** [AgustiCalafellSegura/untitled#9]
Hey, let's go!

Now it's time to learn about another Symfony component. A component is like a library that can be reused. We don't need to reinvent the wheel.

The [Validator](https://symfony.com/doc/current/validation.html) component can **validate** a lot of things. For example, if a given string is an email, or if a given number is greather than other, and more complex constraints.

To install the component, add this line into composer.json file (inside the "require" section)
```json
"symfony/validator": "^3.3"
```

And then execute this command:
```bash
$ composer update
```

Tell me something when you have done it.

**Comment by AgustiCalafellSegura** [comment]
It's done.

**Comment by davidromani** [comment]
@AgustiCalafellSegura always remember to push your commits because I can't see anything...

**Comment by AgustiCalafellSegura** [comment]
![seleccion_015](https://user-images.githubusercontent.com/31628026/32540744-e0c08c3e-c46d-11e7-8d54-60b6f0c59d2d.png)

**Comment by AgustiCalafellSegura** [comment]
![seleccion_016](https://user-images.githubusercontent.com/31628026/32540748-e4a3ac64-c46d-11e7-8879-8758a8fc3b6c.png)

**Comment by davidromani** [comment]
@AgustiCalafellSegura the `require` section is an array, so you must write a `,` between lines.

**Comment by davidromani** [comment]
Check my repositories [here](https://github.com/Flexible-User-Experience), all of them had complex `composer.json` examples.

**Comment by AgustiCalafellSegura** [comment]
Okey. Thanks for the help!!

**Comment by davidromani** [comment]
@AgustiCalafellSegura ok, now let's go to use this new component (Validator). 

Modify the source code in command `app:string:analyzer` to validate that the input string has more than 3 characters. Follow [this](https://symfony.com/doc/current/components/validator.html#usage) example.
